name: macproqc-helpers
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - bioconda::libopenms = 3.2.0
  - conda-forge::mono ~= 6.12
  - conda-forge::compilers = 1.8.0
  - pip:
    - -e .
